### ISSUE TITLE
Add support to select date for the expense

### ISSUE THREAD

**Issue by TomasAndersonFang** [DFY-NCSU/CoinCanvas#24]
For the existing project, @TomasAndersonFang and @TheFatBlue found that we can only create just-in-time expenses, and we both think that it's unreasonable since users cannot keep when they finish consumption. Hence, we decide to add this feature.

**Comment by TomasAndersonFang** [comment]
@TheFatBlue, I already added support to the feature of date selection, but I also realized that since I modified the backend code, some tests might fail. So, could you please check your tests and ensure all of them can pass?

**Comment by TomasAndersonFang** [comment]
@TheFatBlue When u solve, please call me to submit a pr.

**Comment by TheFatBlue** [comment]
I solved it by pushing a commit to `add_date_supporting`, now you can create a pr

**Comment by TomasAndersonFang** [comment]
> I solved it by pushing a commit to `add_date_supporting`, now you can create a pr

Thanks for your fast solution :)
