### ISSUE TITLE
Add tests for the feature of group expense and fix the potential bug

### ISSUE THREAD

**Issue by TomasAndersonFang** [DFY-NCSU/CoinCanvas#30]
since we add group function to the backend, I add some test cases for this. and I found and fix some logical bugs in it:

- when adding expenses to a group, the backend doesn't check if the user belong to the group.
- when get the group expenses, the backend does not check the validity of some parameters (limit and skip)

**Comment by TomasAndersonFang** [comment]
Some tests help us find the potential bugs:

See details in https://github.com/DFY-NCSU/CoinCanvas/pull/29#issuecomment-2499712321

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added checks for user group membership when adding expenses to a group and validated the limit and skip parameters when getting group expenses. Also added new endpoints for group-related expense operations.

You can review changes in this commit: https://github.com/lkilu6456546/DFY-NCSU-CoinCanvas-30/commit/5b906a3e4e0a81222fd28a1a74d6103fe3eb0879.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
