### ISSUE TITLE
Add Extra test case for Read Group Expense

### ISSUE THREAD

**Issue by IMYXR** [DFY-NCSU/CoinCanvas#42]
#### Test Case: Retrieve Expenses with Invalid Authorization Header
**Description:** Tests the behavior of the API when an invalid token is used in the authorization header.  
**Steps:**
1. Use an invalid token in the `Authorization` header.
2. Make a GET request to the `/expenses/` endpoint.
3. Check the status code of the response.
**Expected Result:** The API should return a 403 (Forbidden) response.  

#### Test Case: Retrieve Expenses Filtered by Category
**Description:** Verifies that the API correctly filters expenses by category.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Provide a category filter (`Food`) as a query parameter in the GET request.
3. Check the response data for the `category` field.
**Expected Result:** Only expenses of the specified category should be returned.  

#### Test Case: Retrieve Expenses Sorted by Amount
**Description:** Checks if the API returns expenses sorted by their amount in ascending order.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Provide a `sort=amount` query parameter in the GET request.
3. Check the `amount` field of the returned data to ensure it is sorted.
**Expected Result:** Expenses should be sorted from the smallest to the largest amount.  

#### Test Case: Retrieve Expenses from an Empty Group
**Description:** Tests the API's response when querying expenses for a group that has no expenses.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Query expenses for a group with no expenses.
3. Check the response data for the absence of entries.
**Expected Result:** The API should return an empty list.  

#### Test Case: Retrieve Expenses with Partial Data
**Description:** Verifies that expenses with missing optional fields are handled correctly.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Query expenses for a group where some entries have missing optional fields.
3. Check the response data for missing or `None` fields.
**Expected Result:** Expenses should still be returned, and missing fields should be `None` or excluded.  

#### Test Case: Retrieve Expenses with Duplicate Entries
**Description:** Ensures that no duplicate expenses are returned by the API.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Query expenses for a group where duplicate records are present.
3. Check the IDs of the returned data to ensure uniqueness.
**Expected Result:** All returned expenses should have unique IDs.  

#### Test Case: Retrieve Expenses with Future Dates
**Description:** Validates that expenses with future dates are correctly handled.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Query expenses for a group where some entries have future dates.
3. Check the `date` field to ensure all dates are not in the future.
**Expected Result:** No expenses should have a date in the future.  

#### Test Case: Retrieve Expenses from a Group with Many Entries
**Description:** Ensures that the API can handle and return a large dataset of expenses.  
**Steps:**
1. Use a valid token in the `Authorization` header.
2. Query expenses for a group with a large dataset.
3. Check the number of returned entries and API performance.
**Expected Result:** All expected expenses should be returned without performance issues.  

#### Test Case: Retrieve Expenses as Read-Only User
**Description:** Verifies that a user with read-only permissions can retrieve expenses.  
**Steps:**
1. Use a token with read-only permissions in the `Authorization` header.
2. Query expenses for a group.
3. Check the response data and ensure proper retrieval.
**Expected Result:** The API should return expenses successfully.

**Comment by TomasAndersonFang** [comment]
@IMYXR If you really want to add new tests, please add them for the frontend. Now, the backend already has enough test cases.

**Comment by TheFatBlue** [comment]
Closed due to inactivity
