### ISSUE TITLE
Missing Required Dependency: email-validator

### ISSUE THREAD

**Issue by TheFatBlue** [DFY-NCSU/CoinCanvas#6]
**Description**
When running the project after installing dependencies from `requirements.txt` as instructed [here](https://github.com/DFY-NCSU/CoinCanvas/issues/3#issuecomment-2477509247), the application fails to start due to a missing `email-validator` package. This package is required by Pydantic for email field validation but is not included in the requirements file.

**Error Message**
```
ImportError: email-validator is not installed, run `pip install pydantic[email]`
```

**Steps to Reproduce**
1. Enter the backend directory: `cd backend`
2. Install dependencies: `pip install -r requirements.txt`
3. Run the project: `uvicorn app.main:app --reload`
4. Application fails to start with the above error

**Current Requirements**
The current requirements file includes:

- fastapi==0.104.1
- uvicorn==0.24.0
- sqlalchemy==2.0.23
- pydantic==2.4.2
- python-dotenv==1.0.0
- python-jose==3.3.0
- passlib==1.7.4
- python-multipart==0.0.6
- bcrypt==4.0.1
- alembic==1.12.1

**Proposed Solution**
Add either:
- `email-validator` package directly to `requirements.txt`
OR
- Update the pydantic requirement to include email validation: `pydantic[email]`

**Additional Notes**
There's also a warning about Pydantic V2 config changes that might need attention:
- 'orm_mode' has been renamed to 'from_attributes'

**Comment by TomasAndersonFang** [comment]
I'm sorry I fixed this problem locally but I forgot to update the `requirements.txt` file. @TheFatBlue  Could you update it?@

**Comment by TomasAndersonFang** [comment]
@TheFatBlue Another suggestion is that please create an issue from our [project plan](https://github.com/orgs/DFY-NCSU/projects/2/views/1) :)
